<Project>
	<PropertyGroup>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

		<OutputType>Library</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<Deterministic>true</Deterministic>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>embedded</DebugType>
		<FileAlignment>512</FileAlignment>

		<LangVersion>Preview</LangVersion>

		<!-- Disable packing by default, individual projects can override with <IsPackable>true</IsPackable> -->
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<Optimize>true</Optimize>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<!--Delete unnecessary .deps.json file in build output since it's not used in plugins-->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Delete Files="$(OutputPath)\$(MSBuildProjectName).deps.json" />
	</Target>
</Project>
