<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<OutputPath>..\bin\KK\Patcher\</OutputPath>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="IllusionLibs.BepInEx" Version="5.4.22">
		  <IncludeAssets>compile</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Mono.Cecil" Version="0.10.4">
		  <IncludeAssets>compile</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>