<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>KKS_VR</RootNamespace>
		<AssemblyName>KKS_MainGameVR</AssemblyName>
		<OutputPath>..\bin\KKS\</OutputPath>
		<DefineConstants>TRACE;DEBUG;KKS;GAME;</DefineConstants>
	</PropertyGroup>
	<PropertyGroup>
		<PostBuildEvent>IF EXIST "$(SolutionDir)PostBuild.bat" CALL "$(SolutionDir)PostBuild.bat" "$(TargetDir)\KKS_MainGameVR.dll" KKS</PostBuildEvent>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\LICENSE">
			<Link>LICENSE</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\README.md">
			<Link>README.md</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<EmbeddedResource Include="..\Shared\Fixes\Mirror\mirror-shader" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\Images\credits.txt">
			<Link>Images\credits.txt</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\cursor.png">
			<Link>Images\cursor.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_call.png">
			<Link>Images\icon_call.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_call_xz.png">
			<Link>Images\icon_call_xz.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_gripmove.png">
			<Link>Images\icon_gripmove.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_hand.png">
			<Link>Images\icon_hand.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_hand_1.png">
			<Link>Images\icon_hand_1.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_hand_2.png">
			<Link>Images\icon_hand_2.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_play.png">
			<Link>Images\icon_play.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_school.png">
			<Link>Images\icon_school.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_school_1.png">
			<Link>Images\icon_school_1.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_school_2.png">
			<Link>Images\icon_school_2.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_settings.png">
			<Link>Images\icon_settings.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\Images\icon_warp.png">
			<Link>Images\icon_warp.png</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="KK_FinalIK, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\Libs\KK_FinalIK.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Subsystem.Registration">
			<HintPath>..\VRGIN_OpenXR\Libs\Unity.Subsystem.Registration.dll</HintPath>
		</Reference>
		<Reference Include="Unity.XR.Management">
			<HintPath>..\VRGIN_OpenXR\Libs\Unity.XR.Management.dll</HintPath>
		</Reference>
		<Reference Include="Unity.XR.OpenVR">
			<HintPath>..\VRGIN_OpenXR\Libs\Unity.XR.OpenVR.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpatialTracking">
			<HintPath>..\VRGIN_OpenXR\Libs\UnityEngine.SpatialTracking.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XR.LegacyInputHelpers">
			<HintPath>..\VRGIN_OpenXR\Libs\UnityEngine.XR.LegacyInputHelpers.dll</HintPath>
		</Reference>
		<Reference Include="Valve.Newtonsoft.Json">
			<HintPath>..\VRGIN_OpenXR\Libs\Valve.Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="WindowsInput">
			<HintPath>..\VRGIN_OpenXR\Libs\WindowsInput.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="IllusionLibs.KoikatsuSunshine.AllPackages" Version="*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>compile</IncludeAssets>
		</PackageReference>
		<PackageReference Include="IllusionModdingAPI.KKSAPI" Version="1.41.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>compile</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\VRGIN_OpenXR\VRGIN_OpenXR.csproj">
			<ExcludeAssets>all</ExcludeAssets>
			<IncludeAssets>compile</IncludeAssets>
		</ProjectReference>
	</ItemGroup>
	<Import Project="..\Shared\Shared.projitems" Label="Shared" />
	<Import Project="..\SharedGame\SharedGame.projitems" Label="Shared" />
</Project>