<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<RootNamespace>KK_VR</RootNamespace>
		<AssemblyName>KoikatuVR</AssemblyName>
		<OutputPath>..\bin\KK\</OutputPath>
		<DefineConstants>TRACE;DEBUG;KK;STUDIO;</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\VRGIN\VRGIN\VRGIN.csproj">
			<ExcludeAssets>all</ExcludeAssets>
			<IncludeAssets>compile</IncludeAssets>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="IllusionLibs.Koikatu.AllPackages" Version="*">
			<ExcludeAssets>all</ExcludeAssets>
			<IncludeAssets>compile</IncludeAssets>
		</PackageReference>
		<PackageReference Include="IllusionModdingAPI.KKAPI" Version="1.41.0">
			<ExcludeAssets>all</ExcludeAssets>
			<IncludeAssets>compile</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<Import Project="..\SharedStudio\SharedStudio.projitems" Label="Shared" />
	<Import Project="..\Shared\Shared.projitems" Label="Shared" />
</Project>