<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>KKS_VR</RootNamespace>
		<AssemblyName>KKS_CharaStudioVR</AssemblyName>
		<DefineConstants>TRACE;DEBUG;KKS CharaStudio</DefineConstants>
		<OutputPath>..\bin\KKS\</OutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<PostBuildEvent>IF EXIST "$(SolutionDir)PostBuild.bat" CALL "$(SolutionDir)PostBuild.bat" "$(TargetDir)\KKS_CharaStudioVR.dll" KKS</PostBuildEvent>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="..\Shared\Fixes\Mirror\Manager.cs">
			<Link>Fixes\Mirror\Manager.cs</Link>
		</Compile>
		<Compile Include="..\Shared\Fixes\Mirror\VRReflection.cs">
			<Link>Fixes\Mirror\VRReflection.cs</Link>
		</Compile>
		<EmbeddedResource Include="Util\ColorZOrderShader" />
		<EmbeddedResource Include="..\Shared\Fixes\Mirror\mirror-shader" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="KK_FinalIK">
			<HintPath>..\Libs\KK_FinalIK.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Subsystem.Registration">
			<HintPath>..\VRGIN_OpenXR\Libs\Unity.Subsystem.Registration.dll</HintPath>
		</Reference>
		<Reference Include="Unity.XR.Management">
			<HintPath>..\VRGIN_OpenXR\Libs\Unity.XR.Management.dll</HintPath>
		</Reference>
		<Reference Include="Unity.XR.OpenVR">
			<HintPath>..\VRGIN_OpenXR\Libs\Unity.XR.OpenVR.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpatialTracking">
			<HintPath>..\VRGIN_OpenXR\Libs\UnityEngine.SpatialTracking.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XR.LegacyInputHelpers">
			<HintPath>..\VRGIN_OpenXR\Libs\UnityEngine.XR.LegacyInputHelpers.dll</HintPath>
		</Reference>
		<Reference Include="Valve.Newtonsoft.Json">
			<HintPath>..\VRGIN_OpenXR\Libs\Valve.Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="WindowsInput">
			<HintPath>..\VRGIN_OpenXR\Libs\WindowsInput.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="IllusionLibs.KoikatsuSunshine.AllPackages" Version="*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>compile</IncludeAssets>
		</PackageReference>
		<PackageReference Include="IllusionModdingAPI.KKSAPI" Version="1.41.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>compile</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\VRGIN_OpenXR\VRGIN_OpenXR.csproj">
			<ExcludeAssets>all</ExcludeAssets>
			<IncludeAssets>compile</IncludeAssets>
		</ProjectReference>
	</ItemGroup>
</Project>